### ISSUE TITLE
Allow using all flake refs

### ISSUE THREAD

**Issue by SuperSandro2000** [tweag/nixtract#5]
**Is your feature request related to a problem? Please describe.**

I can't get the graph of my system configuration

```
 ▶ nix shell github:tweag/nixtract
 ▶ nixtract --target-flake-ref .#nixosConfigurations.carbon.config.system.build.toplevel -
error:
       … while evaluating the file '/nix/store/3834gczx1adqj7f8ifna3a0wa080c8y6-python3.10-nixtract-0.1.0/lib/python3.10/site-packages/nixtract/find-attribute-paths.nix':

       … while evaluating a branch condition

         at /nix/store/3834gczx1adqj7f8ifna3a0wa080c8y6-python3.10-nixtract-0.1.0/lib/python3.10/site-packages/nixtract/lib.nix:25:10:

           24|       [ v ]
           25|     else if nixpkgs.lib.isAttrs v then
             |          ^
           26|       nixpkgs.lib.concatMap (collect pred) (nixpkgs.lib.attrValues v)

       … while calling the 'isAttrs' builtin

         at /nix/store/3834gczx1adqj7f8ifna3a0wa080c8y6-python3.10-nixtract-0.1.0/lib/python3.10/site-packages/nixtract/lib.nix:25:13:

           24|       [ v ]
           25|     else if nixpkgs.lib.isAttrs v then
             |             ^
           26|       nixpkgs.lib.concatMap (collect pred) (nixpkgs.lib.attrValues v)

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: flake reference '.#nixosConfigurations.carbon.config.system.build.toplevel' is not an absolute path
```

**Describe the solution you'd like**
That this is supported.

**Describe alternatives you've considered**
I also tried `` ▶ nixtract --target-flake-ref /etc/nixos#nixosConfigurations.carbon.config.system.build.toplevel -``

**Additional context**

**Comment by GuillaumeDesforges** [comment]
Hey @SuperSandro2000 !

Have you tried removing the `#` and things beyond?

```
nixtract --target-flake-ref .
```

I think the flake reference should only be `.`. The rest `nixosConfigurations.carbon.config.system.build.toplevel` is an attribute path and is not what would be part of the flake reference (which can be `.`, `path:some/path` or `github:some/repo`).

**Comment by SuperSandro2000** [comment]
So I can only extract everything and not just from a specific host?

**Comment by GuillaumeDesforges** [comment]
Correct, you can only specify a flake reference (see https://nixos.org/manual/nix/unstable/command-ref/new-cli/nix3-flake#flake-references).

> Flake references (flakerefs) are a way to specify the location of a flake.

At the moment `nixtract` works on a whole flake. This can be improved.
I created issues to track two ideas that are relevant to what you want to achieve:
- https://github.com/tweag/nixtract/issues/8
- https://github.com/tweag/nixtract/issues/7
Pull Requests are welcome :wink: 

In the meantime, a workaround would be to write another flake that has only the output you want to extract the information of.

**Comment by GuillaumeDesforges** [comment]
I'm closing this issue since I think the two issues supersede this one.
