### ISSUE TITLE
Extract for specific flake outputs

### ISSUE THREAD

**Issue by GuillaumeDesforges** [tweag/nixtract#8]
**Is your feature request related to a problem? Please describe.**
At the moment nixtract can only run on a whole flake, but I want to use it to extract information from specific outputs of a flake.

For instance, I may be interested in only extracting information for `nixpkgs#hello`.

Another example, I may be interested in extracting information for `nixpkgs#python39` and `nixpkgs#python310`.

**Describe the solution you'd like**
CLI options to select one or many flake outputs.

**Comment by ErinvanderVeen** [comment]
Is this solved with #10 ?
